config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "targets#index"
  resources :targets, only: [:new, :create, :show, :edit, :update, :destroy] do
    resources :achieves, only: [:create, :destroy]
    resources :fights, only: [:create, :destroy]
  end
end

app/models/achieve.rb
class Achieve < ApplicationRecord
  belongs_to :target

  validates :target_id, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/fight.rb
class Fight < ApplicationRecord
  belongs_to :user
  belongs_to :target

  validates_uniqueness_of :target_id, scope: :user_id
end

app/models/target.rb
class Target < ApplicationRecord
  belongs_to :user
  has_one    :achieve, dependent: :destroy
  has_many   :fights, dependent: :destroy

  with_options presence: true do
    validates :content
    validates :target_date
    validates :user
  end

  def already_achieved?(target)
    Achieve.exists?(target_id: target.id)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :free_time, presence: true
  validates :private_mode, inclusion: { in: [true, false] }

  has_many :targets
  has_many :fights, dependent: :destroy
end

app/controllers/achieves_controller.rb
class AchievesController < ApplicationController
  def create
    @achieve = Achieve.create(target_id: params[:target_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @target = Target.find(params[:target_id])
    @achieve = Achieve.find_by(target_id: @target.id)
    @achieve.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, except: [:index, :show]

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :free_time, :private_mode])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :free_time, :private_mode])
  end
end

app/controllers/fights_controller.rb
class FightsController < ApplicationController
  before_action :set_fight

  def create
    @fight = current_user.fights.create(target_id: params[:target_id])
  end

  def destroy
    @fight = current_user.fights.find_by(target_id: @target.id)
    @fight.destroy
  end

  private

  def set_fight
    @target = Target.find(params[:target_id])
  end
end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  before_action :set_user_where, only: [:index, :show]
  before_action :set_current_user, only: [:new, :edit]
  before_action :set_user_find_id, only: :show
  before_action :set_targets, only: [:new, :show, :edit]
  before_action :set_target_find_id, only: [:edit, :update, :destroy, :move_to_index]
  before_action :move_to_index, only: [:edit, :update, :destroy]

  def index
  end

  def new
    @target = Target.new
  end

  def create
    @target = Target.create(target_params)
    if @target.save
      redirect_to action: :new
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def show
  end

  def edit
  end

  def update
    if @target.update(target_params)
      redirect_to action: :new
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @target.destroy
    redirect_back(fallback_location: root_path)
  end

  def set_user_where
    @users = User.where(private_mode: 0)
  end

  def set_current_user
    @user = User.find(current_user.id)
  end

  def set_user_find_id
    @user = User.find(params[:id])
  end

  def set_targets
    @targets = @user.targets.order('target_date DESC').includes(:user)
  end

  def set_target_find_id
    @target = Target.find(params[:id])
  end

  def move_to_index
    redirect_to action: :index unless current_user.id == @target.user_id
  end

  private

  def target_params
    params.require(:target).permit(:target_date, :content, :achieve).merge(user_id: current_user.id)
  end
end

app/helpers/achieves_helper.rb
module AchievesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fights_helper.rb
module FightsHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/fights/_fight.html.erb
<% if user_signed_in? %>
  <%= target.fights.count %>
  <% if current_user.fights.find_by(target_id: target.id) %>
    <%= link_to target_fight_path(target, target), method: :delete, remote: true, class:"fight" do %>
      <q>ガンバ！</q><i class="fas fa-heart"></i>
    <% end %>
  <% else %>
    <%= link_to target_fights_path(target), method: :post, remote: true, class:"fight" do %>
      <q>ガンバ！</q><i class="far fa-heart"></i>
    <% end %>
  <% end %>
<% end %>

app/views/fights/create.js.erb
$('#fight-<%= @target.id %>').html('<%= escape_javascript(render("fights/fight", target: @target )) %>');

app/views/fights/destroy.js.erb
$('#fight-<%= @target.id %>').html('<%= escape_javascript(render("fights/fight", target: @target )) %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyLifeGame</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/e36cf7eb91.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<%= form_with model: @target, class: 'form-group', local: true do |f| %>
  <div class="input-wrap">
    <div class='target-date-wrap'>
      <p class="form-label">Target</p>
        <%= raw sprintf(
                  f.date_select(
                    :target_date,
                    class:'target-date',
                    id:"target-date",
                    use_month_numbers: true,
                    start_year: 1970,
                    end_year: (Time.now.year + 200),
                    date_separator: '%s'),
                  "<span>年&nbsp;</span>", "<span>月&nbsp;</span>") + "<span>日</span>" %>
      </div>
    <div class="content">
      <%= f.text_area :content, placeholder: "目標またはステータスを入力" %>
    </div>
  </div>
  <%= f.submit '送信', class: 'form-submit' %>
<% end %>

app/views/shared/_header.html.erb
<div class="header">
  <div class="logo">
    <%= link_to "My Life Game", root_path, class: "logo" %>
  </div>
  <div class="devise-nav">
    <% if current_page?('/users/sign_up') %>
      <%= link_to "log-in", new_user_session_path , class: "nav-link" %>
      <%= link_to "top-page", root_path, class: "nav-link" %>
    <% elsif current_page?('/users/sign_in') %>
      <%= link_to "sign-up", new_user_registration_path , class: "nav-link" %>
      <%= link_to "top-page", root_path, class: "nav-link" %>
    <% elsif user_signed_in? %>
      <%= link_to "user-edit", edit_user_registration_path(current_user) , class: "nav-link" %>
      <%= link_to "log-out", destroy_user_session_path, method: :delete , class: "nav-link" %>
      <%= link_to "top-page", root_path , class: "nav-link"%>
    <% else %>
      <%= link_to "log-in", new_user_session_path , class: "nav-link" %>
      <%= link_to "sign-up", new_user_registration_path , class: "nav-link" %>
    <% end %>
  </div>
</div>

app/views/shared/_main.html.erb
<div class="main">
  <div class="upper-main">
    <div class="name">
      <p class="name-label">name</p>
      <%= @user.name %>
    </div>
    <div class="free-time-wrapper">
      <p>free-time<p>
      <div class="free-time", id="free-time"> 
        <%= @user.free_time.strftime("%H:%M") %>
      </div>
    </div>
    <div class="count-down">
      <p>countdown</p>
      <div class="count-down-icon">
        <i class="far fa-clock", id="remaining-date"></i>   
        <i class="fas fa-user-clock", id="remaining-free-time"></i>
        <i class="far fa-stop-circle", id="stop-time"></i>
      </div>
    </div>
  </div>

  <ul class="targets"><h3 class="section">ターゲット</h3>
    <% @targets.each do |target| %>
      <% unless target.achieve %>
        <li class="target">
          <div class="upper-target">
            <div class="target-date" ,id="targetDate"><%= target.target_date %></div>
            <div class="remaining-time", id='remaining-time'></div>
          </div>
          <div class="middle-target">
            <div class="target-content">
              <%= target.content %>
            </div>
          </div>
          <div class="lower-target">
            <div id="fight-<%= target.id%>">
              <%= render 'fights/fight', target: target %>
            </div>
            <% if user_signed_in? && current_user.id == @user.id %>
              <div class="target-achieve">
                <% unless target.already_achieved?(target) %>
                  <%= link_to target_achieves_path(target), method: :post, class: "achieve" do %>
                    <q>GET </q><i class="far fa-square"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="target-edit">
                <%= link_to edit_target_path(target.id), class: "edit" do %>
                  <i class="far fa-edit"></i>
                <% end %>
              </div>
              <div class="target-delete">
                <%= link_to target_path(target.id), method: :delete, data: {confirm: "本当に削除しますか？"}, class: "delete" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </li>  
      <% end %>
    <% end %>    
  </ul>

  <ul class="achieves"><h3 class="section">ステータス</h3>
    <% @targets.each do |target| %>
      <% if target.achieve %>
        <li class="target" target-id=<%= target.id %>>
          <div class="upper-target">
            <div class="skill-date" ,id="skillDate"><%= target.target_date %></div>
          </div>
          <div class="middle-target">
            <div class="target-content">
              <%= target.content %>
            </div>
          </div>
          <div class="lower-target">
            <div id="fight-<%= target.id%>">
              <%= render 'fights/fight', target: target %>
            </div>
            <% if user_signed_in? && current_user.id == @user.id %>
              <div class="target-achieve">
                <% if target.already_achieved?(target) %>
                  <%= link_to  target_achiefe_path(target, target), method: :delete, class: "achieve" do %>
                    <q>GET </q><i class="fas fa-check-square"></i>
                  <% end %>
                <% end %>
              </div>
              <div class="target-edit">
                <%= link_to edit_target_path(target.id), class: "edit" do %>
                  <i class="far fa-edit"></i>
                <% end %>
              </div>
              <div class="target-delete">
                <%= link_to target_path(target.id), data: {confirm: "本当に削除しますか？"}, method: :delete, class: "edit" do %>
                  <i class="fas fa-trash-alt"></i>
                <% end %>
              </div>
            <% end %>
          </div>
        </li>  
      <% end %>    
    <% end %>    
  </ul>
                
</div>

app/views/shared/_side_bar.html.erb
<table  class="side-bar">
  <thead>
    <tr><th>
    <tr><th>
    <% if user_signed_in? %>
    <%= link_to "マイページ", new_target_path(current_user), class: "page-nav" %>
    <% else %>
    <%= link_to "ログイン",                      new_user_session_path, class: "page-nav" %>
    <% end %>
     </th></tr>
  </thead>
  <tbody>
  <tr><td class="names">names</td></tr>   
    <% @users.each do |user| %>
      <tr><td>
      <%= link_to user.name, target_path(user.id), class: "name-nav" %>
      </td></tr>   
    <% end %>
  </tbody>
</table>

app/views/targets/edit.html.erb
<div class="new-wrapper">
  <div class="new-header">
    <%= render "shared/header" %>
  </div>
  <div class="new-main">
    <%= render "shared/main" %>
  </div>
  <div class="new-form">
    <%= render "shared/form" %>
  </div>
</div>

app/views/targets/index.html.erb
<div class="index-wrapper">
  <div class="index-side-bar">
    <%= render "shared/side_bar" %>
  </div>
  <div class="index-main-bar">
    <div class="index-header">
      <%= render "shared/header" %>
    </div>
  </div>
</div>

app/views/targets/new.html.erb
<div class="new-wrapper">
  <div class="new-header">
    <%= render "shared/header" %>
  </div>
  <div class="new-main">
    <%= render "shared/main" %>
  </div>
  <div class="new-form">
    <%= render "shared/form" %>
  </div>
</div>

app/views/targets/show.html.erb
<div class="show-wrapper">
  <div class="show-side-bar">
    <%= render "shared/side_bar" %>
  </div>
  <div class="show-main-bar">
    <div class="show-header">
      <%= render "shared/header" %>
    </div>
    <div class="show-main">
      <%= render "shared/main" %>
    </div>
  </div>
</div>